script: mvn test
after_success:
- openssl aes-256-cbc -K $encrypted_47edfc36d970_key -iv $encrypted_47edfc36d970_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git config --global user.name "travis-ci"
- git config --global user.email "noreply@travis-ci.org"
- source publish-on-gh-pages.sh
